name: twitter_webview_auth
description: Twitter oauth1 webview authentication implemention using webview_flutter
version: 0.2.0
homepage: https://github.com/robertodoering/twitter_webview_auth

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  oauth1: ^2.0.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.0.3
  build_runner: ^2.1.7
